const fs = require('fs');
let code = fs.readFileSync('backend/server.js', 'utf8');

const start = code.indexOf('    mfInitializationPromise = (async () => {');
const end = code.indexOf('    })();', start) + '    })();'.length;

const before = code.substring(0, start);
const after = code.substring(end);

const newInit = "    mfInitializationPromise = (async () => {\n        try {\n            console.log('Fetching master list from amfiindia.com (Filtered for active direct growth only)...');\n            const amfiRes = await myFetch('https://www.amfiindia.com/spages/NAVAll.txt');\n            const amfiText = await amfiRes.text();\n            \n            const funds = [];\n            const lines = amfiText.split('\\n');\n            for (const line of lines) {\n                if (line.includes(';')) {\n                    const parts = line.split(';');\n                    if (parts.length >= 4 && parts[0] && !isNaN(parts[0])) {\n                        let schemeName = parts[3].trim();\n                        if (parts.length >= 6 && parts[4] && parts[5]) {\n                            schemeName += ' - ' + parts[4].trim() + ' - ' + parts[5].trim();\n                        } else if (parts.length >= 5 && parts[4]) {\n                            schemeName += ' - ' + parts[4].trim();\n                        }\n                        \n                        const n = schemeName.toLowerCase();\n                        // FILTER: Keep only Direct Growth retail funds (< 2000 items)\n                        if (\n                            n.includes('growth') &&\n                            n.includes('direct') &&\n                            !n.includes('regular') &&\n                            !n.includes('etf') &&\n                            !n.includes('fmp') &&\n                            !n.includes('fixed maturity')\n                        ) {\n                            funds.push({\n                                schemeCode: parseInt(parts[0].trim()),\n                                schemeName: schemeName\n                            });\n                        }\n                    }\n                }\n            }\n            \n            allMutualFunds = funds;\n            console.log(`Successfully parsed ${allMutualFunds.length} highly active retail mutual funds from AMFI.`);\n            \n        } catch (err) {\n            console.error('Failed to fetch mutual funds master list:', err.message);\n        } finally {\n            mfInitializationPromise = null;\n        }\n    })();";

fs.writeFileSync('backend/server.js', before + newInit + after);
